<a href="https://colab.research.google.com/github/infyprakash/algorithmic-trading/blob/main/vectorized_backtesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# vectorization with pandas

In [2]:
a = np.arange(15).reshape(5,3)

In [3]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
columns = list("ABC")
index = pd.date_range('2022-4-1',periods=5,freq='B')

In [8]:
columns

['A', 'B', 'C']

In [9]:
index

DatetimeIndex(['2022-04-01', '2022-04-04', '2022-04-05', '2022-04-06',
               '2022-04-07'],
              dtype='datetime64[ns]', freq='B')

In [10]:
df = pd.DataFrame(a,columns=columns,index=index)

In [11]:
df

A   B   C
2022-04-01   0   1   2
2022-04-04   3   4   5
2022-04-05   6   7   8
2022-04-06   9  10  11
2022-04-07  12  13  14

In [12]:
2 * df

A   B   C
2022-04-01   0   2   4
2022-04-04   6   8  10
2022-04-05  12  14  16
2022-04-06  18  20  22
2022-04-07  24  26  28

In [13]:
df.sum()

A    30
B    35
C    40
dtype: int64

In [14]:
np.mean(df)

A    6.0
B    7.0
C    8.0
dtype: float64

In [16]:
df['A'] + df['B']

2022-04-01     1
2022-04-04     7
2022-04-05    13
2022-04-06    19
2022-04-07    25
Freq: B, dtype: int64

In [17]:
df['A'] > 5

2022-04-01    False
2022-04-04    False
2022-04-05     True
2022-04-06     True
2022-04-07     True
Freq: B, Name: A, dtype: bool

In [18]:
df[df['A'] > 5]

A   B   C
2022-04-05   6   7   8
2022-04-06   9  10  11
2022-04-07  12  13  14